extern uint16_t FONE_COLOR;
extern uint16_t TEXT_COLOR;


// 'AudioOFF', 9x7px
const uint16_t bitmap_AudioOFF [] PROGMEM = {
	FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, 
	FONE_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, 
	FONE_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, 
	TEXT_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR
};
// 'AudioON', 8x7px
const uint16_t bitmap_AudioON [] PROGMEM = {
	FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, 
	TEXT_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, 
	TEXT_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, 
	FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, FONE_COLOR
};
// 'CheckOFF', 14x14px
const uint16_t bitmap_CheckOFF [] PROGMEM = {
	TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, 
	TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, 
	FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, 
	FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, 
	FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, 
	FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, 
	TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, 
	TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, 
	FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, 
	FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, 
	FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, 
	TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, 
	TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR
};
// 'CheckON', 14x14px
const uint16_t bitmap_CheckON [] PROGMEM = {
	TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, 
	TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, 
	FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, 
	TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, 
	TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, 
	TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, 
	TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, 
	TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, 
	FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, 
	TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, 
	FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, FONE_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, 
	TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, 
	TEXT_COLOR, TEXT_COLOR, TEXT_COLOR, TEXT_COLOR
};